CONDA_BUILD_SYSROOT:
  - /opt/MacOSX15.5.sdk  # [osx]

SDKROOT:
  - /opt/MacOSX15.5.sdk  # [osx]

MACOSX_DEPLOYMENT_TARGET:
  - 11.3                 # [osx]

target_platform:                                                                                                        
  - linux-64             # [linux]
  - linux-aarch64        # [linux]
  # - linux-riscv64      # [linux]
  # - osx-64             # [osx]
  - osx-arm64            # [osx]

c_compiler_version:
  - '>=16,<17'           # [linux]
  - '>=23,<24'           # [osx]

cxx_compiler_version:
  - '>=16,<17'           # [linux]
  - '>=23,<24'           # [osx]

clang_format:
  - '>=23,<24'

clangxx:
  - '>=23,<24'

libclang:
  - '>=23,<24'

python:
  - 3.13
  - 3.14

fmt:
  - '>=12.2'

openssl:
  - '>=3.6,<4.0'

libabseil:
   - '>=20260526.0,<20260817.0'  # due to libprotobuf 7.36

cli11:
   - '==2.7.1'  # 2.7.2 fails to link on macos
