target_platform:                                                                                                        
  - linux-aarch64        # [linux]
  - linux-64             # [linux]

fmt:
  - '>=11.0'
